[pytest]
asyncio_mode = auto
testpaths = tests
norecursedirs = .git .github .vscode .ruff_cache config custom_components com.rivian.android.consumer stubhub-setter
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    --strict-markers
    --cov=custom_components.rivian
    --cov-report=term-missing
    --cov-report=html
    --cov-fail-under=78
    --timeout=30
markers =
    asyncio: mark test as async
