"""The generated protobuf modules, and the runtime they will meet.

Every `*_pb2.py` is generated by scripts/regen_proto.sh, committed, and shipped;
Home Assistant never runs protoc. Each one calls ValidateProtobufRuntimeVersion
when it is imported and raises if the installed protobuf is OLDER than the protoc
that wrote it. That is how the integration was taken down during vendoring:
generated code newer than the runtime Home Assistant had pinned.

So the version stamped into the generated code is a promise about which Home
Assistant releases can load the integration, and it is tied here to the two
places that make the same promise: `manifest.json` (the protobuf range) and
`hacs.json` (the Home Assistant floor).
"""

from __future__ import annotations

import importlib
import json
import pathlib
import re

from google.protobuf import descriptor_pool
import pytest

from custom_components.rivian.rivian_client import parallax

REPO = pathlib.Path(__file__).resolve().parents[2]
PROTO_DIR = pathlib.Path(parallax.__file__).parent / "proto"
PROTOS = sorted(PROTO_DIR.glob("*.proto"))
GENERATED = sorted(PROTO_DIR.glob("*_pb2.py"))

# homeassistant/package_constraints.txt at each tag: 2025.5.3 pins protobuf
# 5.29.2, 2025.6.0 pins 6.31.1. The floor is the first release that can import
# code stamped 6.31.1.
HA_FLOOR = "2025.6.0"
HA_FLOOR_PROTOBUF = (6, 31, 1)


def _version(text: str) -> tuple[int, ...]:
    return tuple(int(part) for part in text.split("."))


def _stamp(path: pathlib.Path) -> tuple[int, ...]:
    match = re.search(
        r"^# Protobuf Python Version: ([0-9.]+)$", path.read_text(), re.MULTILINE
    )
    assert match, f"{path.name} carries no version stamp"
    return _version(match.group(1))


def _manifest_protobuf() -> str:
    requirements = json.loads(
        (REPO / "custom_components" / "rivian" / "manifest.json").read_text()
    )["requirements"]
    (declared,) = [r for r in requirements if r.startswith("protobuf")]
    return declared


def test_every_schema_has_its_generated_module_and_no_other() -> None:
    assert PROTOS, "no schemas found"
    assert {p.stem for p in PROTOS} == {g.stem.removesuffix("_pb2") for g in GENERATED}


@pytest.mark.parametrize("path", GENERATED, ids=lambda p: p.name)
def test_generated_module_imports(path: pathlib.Path) -> None:
    importlib.import_module(f"{parallax.__name__}.proto.{path.stem}")


@pytest.mark.parametrize("path", GENERATED, ids=lambda p: p.name)
def test_stamp_is_the_floor_exactly(path: pathlib.Path) -> None:
    """Newer would lock out the floor release; older means a stale toolchain."""
    assert _stamp(path) == HA_FLOOR_PROTOBUF


def test_manifest_admits_the_floor_and_stops_before_the_next_break() -> None:
    declared = _manifest_protobuf()
    lower = re.search(r">=\s*([0-9.]+)", declared)
    upper = re.search(r"<\s*([0-9]+)\b", declared)
    assert lower and upper, declared
    assert _version(lower.group(1)) == HA_FLOOR_PROTOBUF
    # protobuf guarantees a runtime loads code generated by the previous major
    # version and no further back, so 6.x code is good through 7.x and not 8.
    assert int(upper.group(1)) == HA_FLOOR_PROTOBUF[0] + 2


def test_hacs_floor_is_the_release_the_stamp_needs() -> None:
    assert json.loads((REPO / "hacs.json").read_text())["homeassistant"] == HA_FLOOR


def test_regen_script_pins_the_same_stamp() -> None:
    script = (REPO / "scripts" / "regen_proto.sh").read_text()
    assert f'STAMP="{".".join(map(str, HA_FLOOR_PROTOBUF))}"' in script


@pytest.mark.parametrize("path", PROTOS, ids=lambda p: p.name)
def test_schema_is_registered_under_a_name_nothing_else_will_claim(
    path: pathlib.Path,
) -> None:
    """The descriptor pool is process-wide and rejects two files with one name.

    A bare "body.proto", or upstream's "rivian/parallax/proto/body.proto" with
    its `rivian.parallax` package, could collide with another library in Home
    Assistant's interpreter -- upstream's own client included.
    """
    importlib.import_module(f"{parallax.__name__}.proto.{path.stem}_pb2")
    name = f"custom_components/rivian/rivian_client/parallax/proto/{path.name}"
    registered = descriptor_pool.Default().FindFileByName(name)
    assert registered.package == f"rivian_ha.parallax.{path.stem}"


@pytest.mark.parametrize("path", PROTOS, ids=lambda p: p.name)
def test_schema_imports_no_sibling(path: pathlib.Path) -> None:
    """A generated module imports a sibling by absolute package path."""
    assert not re.search(r"^import ", path.read_text(), re.MULTILINE)
