#!/usr/bin/env bash
# Regenerate the protobuf modules from the Parallax .proto schemas.
#
#   scripts/regen_proto.sh           regenerate in place
#   scripts/regen_proto.sh --check   regenerate, then fail if anything changed
#
# The generated *_pb2.py are COMMITTED and shipped; Home Assistant does not run
# protoc. That makes two things load-bearing, and this script enforces both.
#
# 1. The version stamped into the generated code. Every *_pb2.py calls
#    ValidateProtobufRuntimeVersion at import and raises if the installed
#    protobuf is OLDER than the generator's. That is what took the integration
#    down during vendoring: code generated by a newer protoc than the runtime
#    Home Assistant had pinned. So the stamp is pinned to STAMP below, which is
#    the protobuf of the oldest Home Assistant this integration supports
#    (hacs.json), and a regeneration that produces anything else is refused.
#    Bumping grpcio-tools is therefore a decision to raise the HA floor --
#    change STAMP, manifest.json and hacs.json together, never one alone.
#
# 2. The name each schema is registered under. protoc records the path relative
#    to --proto_path, and the process-wide descriptor pool rejects two different
#    files with one name. --proto_path is the repository root so the name is
#    the full custom_components/... path, which nothing else will ever claim;
#    a bare "body.proto" could collide with any other package in Home
#    Assistant's interpreter, upstream's rivian client included.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

STAMP="6.31.1"
PROTO_DIR="custom_components/rivian/rivian_client/parallax/proto"

PY=python3
[ -x .venv/bin/python ] && PY=.venv/bin/python

shopt -s nullglob
PROTOS=("$PROTO_DIR"/*.proto)
if [ ${#PROTOS[@]} -eq 0 ]; then
  echo "regen_proto: no .proto files under $PROTO_DIR"
  exit 0
fi

if ! "$PY" -c "import grpc_tools.protoc" 2>/dev/null; then
  echo "regen_proto: grpcio-tools is not installed for $PY" >&2
  echo "  it is pinned in requirements_test.txt; run scripts/setup_dev_env.sh" >&2
  exit 2
fi

# Remove first, so a deleted or renamed schema cannot leave its module behind.
rm -f "$PROTO_DIR"/*_pb2.py "$PROTO_DIR"/*_pb2.pyi
"$PY" -m grpc_tools.protoc --proto_path=. --python_out=. --pyi_out=. "${PROTOS[@]}"

bad=0
for f in "$PROTO_DIR"/*_pb2.py; do
  if ! grep -q "^# Protobuf Python Version: $STAMP\$" "$f"; then
    echo "regen_proto: $f is not stamped $STAMP:" >&2
    grep -m1 "^# Protobuf Python Version" "$f" >&2 || echo "  (no stamp)" >&2
    bad=1
  fi
done
[ "$bad" -eq 0 ] || exit 1

echo "regen_proto: ${#PROTOS[@]} schemas, stamped $STAMP"

if [ "${1:-}" = "--check" ]; then
  if [ -n "$(git status --porcelain -- "$PROTO_DIR")" ]; then
    echo "regen_proto: generated modules were out of date:" >&2
    git status --short -- "$PROTO_DIR" >&2
    exit 1
  fi
fi
