# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: custom_components/rivian/rivian_client/parallax/proto/geofence.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'custom_components/rivian/rivian_client/parallax/proto/geofence.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nDcustom_components/rivian/rivian_client/parallax/proto/geofence.proto\x12\x1brivian_ha.parallax.geofence\"\xb1\x01\n\x11\x46\x61voriteGeofences\x12I\n\x08geofence\x18\x01 \x03(\x0b\x32\x37.rivian_ha.parallax.geofence.FavoriteGeofences.Geofence\x1aQ\n\x08Geofence\x12\x37\n\x04type\x18\x01 \x01(\x0e\x32).rivian_ha.parallax.geofence.GeofenceType\x12\x0c\n\x04name\x18\x02 \x01(\t*X\n\x0cGeofenceType\x12\x18\n\x14GEOFENCE_TYPE_CUSTOM\x10\x00\x12\x16\n\x12GEOFENCE_TYPE_HOME\x10\x01\x12\x16\n\x12GEOFENCE_TYPE_WORK\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'custom_components.rivian.rivian_client.parallax.proto.geofence_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GEOFENCETYPE']._serialized_start=281
  _globals['_GEOFENCETYPE']._serialized_end=369
  _globals['_FAVORITEGEOFENCES']._serialized_start=102
  _globals['_FAVORITEGEOFENCES']._serialized_end=279
  _globals['_FAVORITEGEOFENCES_GEOFENCE']._serialized_start=198
  _globals['_FAVORITEGEOFENCES_GEOFENCE']._serialized_end=279
# @@protoc_insertion_point(module_scope)
