# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: custom_components/rivian/rivian_client/parallax/proto/secure_file_transfer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'custom_components/rivian/rivian_client/parallax/proto/secure_file_transfer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nPcustom_components/rivian/rivian_client/parallax/proto/secure_file_transfer.proto\x12\'rivian_ha.parallax.secure_file_transfer\"\xf0\x03\n\x15PetSnapshotSecureFile\x12Y\n\x08metadata\x18\x04 \x01(\x0b\x32G.rivian_ha.parallax.secure_file_transfer.PetSnapshotSecureFile.Metadata\x1a\xea\x01\n\x08Metadata\x12Z\n\tfile_type\x18\x02 \x01(\x0e\x32G.rivian_ha.parallax.secure_file_transfer.PetSnapshotSecureFile.FileType\x12\x16\n\tfile_size\x18\x03 \x01(\x04H\x00\x88\x01\x01\x12\\\n\ncreated_at\x18\x04 \x01(\x0b\x32H.rivian_ha.parallax.secure_file_transfer.PetSnapshotSecureFile.CreatedAtB\x0c\n\n_file_size\x1a-\n\tCreatedAt\x12\x14\n\x07seconds\x18\x01 \x01(\x04H\x00\x88\x01\x01\x42\n\n\x08_seconds\"`\n\x08\x46ileType\x12\x19\n\x15\x46ILE_TYPE_UNSPECIFIED\x10\x00\x12\x11\n\rFILE_TYPE_PNG\x10\x01\x12\x12\n\x0e\x46ILE_TYPE_JPEG\x10\x02\x12\x12\n\x0e\x46ILE_TYPE_WEBP\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'custom_components.rivian.rivian_client.parallax.proto.secure_file_transfer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PETSNAPSHOTSECUREFILE']._serialized_start=126
  _globals['_PETSNAPSHOTSECUREFILE']._serialized_end=622
  _globals['_PETSNAPSHOTSECUREFILE_METADATA']._serialized_start=243
  _globals['_PETSNAPSHOTSECUREFILE_METADATA']._serialized_end=477
  _globals['_PETSNAPSHOTSECUREFILE_CREATEDAT']._serialized_start=479
  _globals['_PETSNAPSHOTSECUREFILE_CREATEDAT']._serialized_end=524
  _globals['_PETSNAPSHOTSECUREFILE_FILETYPE']._serialized_start=526
  _globals['_PETSNAPSHOTSECUREFILE_FILETYPE']._serialized_end=622
# @@protoc_insertion_point(module_scope)
