# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: custom_components/rivian/rivian_client/parallax/proto/vehicle_access.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'custom_components/rivian/rivian_client/parallax/proto/vehicle_access.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nJcustom_components/rivian/rivian_client/parallax/proto/vehicle_access.proto\x12!rivian_ha.parallax.vehicle_access\"k\n\x13PassiveEntrySetting\x12T\n\x16\x63\x63\x63_passive_permission\x18\x01 \x01(\x0e\x32\x34.rivian_ha.parallax.vehicle_access.CccPassiveSetting\"\x92\x01\n\x11PassiveEntryState\x12$\n\x1c\x61llow_bluetooth_while_in_ccc\x18\x01 \x01(\x08\x12W\n\x16\x63\x63\x63_passive_permission\x18\x02 \x01(\x0e\x32\x37.rivian_ha.parallax.vehicle_access.CccPassivePermission*{\n\x11\x43\x63\x63PassiveSetting\x12#\n\x1f\x43\x43\x43_PASSIVE_SETTING_UNAVAILABLE\x10\x00\x12 \n\x1c\x43\x43\x43_PASSIVE_SETTING_DISABLED\x10\x01\x12\x1f\n\x1b\x43\x43\x43_PASSIVE_SETTING_ENABLED\x10\x02*\x7f\n\x14\x43\x63\x63PassivePermission\x12\x1e\n\x1a\x43\x43\x43_PASSIVE_PERMISSION_SNA\x10\x00\x12#\n\x1f\x43\x43\x43_PASSIVE_PERMISSION_DISABLED\x10\x01\x12\"\n\x1e\x43\x43\x43_PASSIVE_PERMISSION_ENABLED\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'custom_components.rivian.rivian_client.parallax.proto.vehicle_access_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CCCPASSIVESETTING']._serialized_start=371
  _globals['_CCCPASSIVESETTING']._serialized_end=494
  _globals['_CCCPASSIVEPERMISSION']._serialized_start=496
  _globals['_CCCPASSIVEPERMISSION']._serialized_end=623
  _globals['_PASSIVEENTRYSETTING']._serialized_start=113
  _globals['_PASSIVEENTRYSETTING']._serialized_end=220
  _globals['_PASSIVEENTRYSTATE']._serialized_start=223
  _globals['_PASSIVEENTRYSTATE']._serialized_end=369
# @@protoc_insertion_point(module_scope)
