# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: custom_components/rivian/rivian_client/parallax/proto/vehicle_operation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'custom_components/rivian/rivian_client/parallax/proto/vehicle_operation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nMcustom_components/rivian/rivian_client/parallax/proto/vehicle_operation.proto\x12$rivian_ha.parallax.vehicle_operation\"\xe4\x04\n\x17VehicleOperationRequest\x12X\n\x08metadata\x18\x01 \x01(\x0b\x32\x46.rivian_ha.parallax.vehicle_operation.VehicleOperationRequest.Metadata\x12Z\n\toperation\x18\x02 \x01(\x0b\x32G.rivian_ha.parallax.vehicle_operation.VehicleOperationRequest.Operation\x1a.\n\tPhoneInfo\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x10\n\x08phone_id\x18\x02 \x01(\x0c\x1a{\n\x08Metadata\x12[\n\nphone_info\x18\x01 \x01(\x0b\x32G.rivian_ha.parallax.vehicle_operation.VehicleOperationRequest.PhoneInfo\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x1a\xb8\x01\n\tOperation\x12\x10\n\x08rvm_type\x18\x01 \x01(\t\x12\x16\n\x0eoperation_type\x18\x02 \x01(\x05\x12\x14\n\x0coperation_id\x18\x03 \x01(\x0c\x12\x0f\n\x07payload\x18\x04 \x01(\x0c\x12Z\n\ttimestamp\x18\x05 \x01(\x0b\x32G.rivian_ha.parallax.vehicle_operation.VehicleOperationRequest.Timestamp\x1a+\n\tTimestamp\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x12\r\n\x05nanos\x18\x02 \x01(\x05\".\n\x1bSendVehicleOperationSuccess\x12\x0f\n\x07success\x18\x01 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'custom_components.rivian.rivian_client.parallax.proto.vehicle_operation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VEHICLEOPERATIONREQUEST']._serialized_start=120
  _globals['_VEHICLEOPERATIONREQUEST']._serialized_end=732
  _globals['_VEHICLEOPERATIONREQUEST_PHONEINFO']._serialized_start=329
  _globals['_VEHICLEOPERATIONREQUEST_PHONEINFO']._serialized_end=375
  _globals['_VEHICLEOPERATIONREQUEST_METADATA']._serialized_start=377
  _globals['_VEHICLEOPERATIONREQUEST_METADATA']._serialized_end=500
  _globals['_VEHICLEOPERATIONREQUEST_OPERATION']._serialized_start=503
  _globals['_VEHICLEOPERATIONREQUEST_OPERATION']._serialized_end=687
  _globals['_VEHICLEOPERATIONREQUEST_TIMESTAMP']._serialized_start=689
  _globals['_VEHICLEOPERATIONREQUEST_TIMESTAMP']._serialized_end=732
  _globals['_SENDVEHICLEOPERATIONSUCCESS']._serialized_start=734
  _globals['_SENDVEHICLEOPERATIONSUCCESS']._serialized_end=780
# @@protoc_insertion_point(module_scope)
